Controllers/ExamesController.cs
using Agedamento.Data;
using Agedamento.Models;
using Agendamento.Models;
using Agendamento.Repositorio;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

public class ExamesController : Controller
{
    private readonly IExameRepositorio _exameRepositorio;

    public ExamesController(IExameRepositorio ExameRpositorio)
    {
        _exameRepositorio = ExameRpositorio;
    }

    public IActionResult Index()
    {
        List<ExameModel> exames = _exameRepositorio.BuscarTodos();
        return View(exames);
    }

    public IActionResult Criar()
    {
        return View();
    }
    public IActionResult Editar(int id)
    {
        ExameModel exame = _exameRepositorio.ListarPorId(id);
        return View(exame);
    }
    public IActionResult ApagarConfirmacao(int id)
    {
        ExameModel exame = _exameRepositorio.ListarPorId(id);
        return View(exame);

    }

    public IActionResult Apagar(int id)
    {
        try
        {
            bool apagado = _exameRepositorio.Apagar(id);
            if (apagado)
            {
                TempData["MensagemSucesso"] = " Exame excluido com sucesso!";
            }
            else
            {
                TempData["MensagemErro"] = " Houve um erro ao apagar o exame";

            }
            return RedirectToAction("Index");
        }
        catch (Exception erro)
        {
            TempData["MensagemErro"] = $"Não conseguimos apagar o exame, detalhes do erro: {erro.Message}";
            return RedirectToAction("Index");

        }
    }

    [HttpPost]
    public IActionResult Criar(ExameModel exame)
    {
        try
        {
            if (ModelState.IsValid)
            {
                _exameRepositorio.Adicionar(exame);
                TempData["MensagemSucesso"] = "Exame cadastrado com sucesso";
                return RedirectToAction("Index");
            }
            return View(exame);
        }
        catch (Exception erro)
        {
            TempData["MensagemErro"] = $"Exame não cadastrado, tente novamente. Detalhe do erro {erro.Message}";
            return RedirectToAction("Index");


        }
    }

    [HttpPost]
    public IActionResult Alterar(ExameModel exame)
    {
        try
        {
            if (ModelState.IsValid)
            {
                _exameRepositorio.Atualizar(exame);
                TempData["MensagemSucesso"] = "Exame alterado com sucesso";
                return RedirectToAction("Index");

            }
            return View("Editar", exame);
        }
        catch (Exception erro)
        {
            TempData["MensagemErro"] = $"Não conseguimos atualizar o exame, tente novamente. Detalhe do erro: {erro.Message}";
            return RedirectToAction("Index");
        }
    }
}

Controllers/TipoExamesController.cs
using Agedamento.Data;
using Agedamento.Models;
using Agendamento.Models;
using Agendamento.Repositorio;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

public class TipoExamesController : Controller
{
    private readonly ITipoExamesRepositorio _tipoExamesRepositorio;
    
    public TipoExamesController(ITipoExamesRepositorio TipoExamesRepositorio)
    {
        _tipoExamesRepositorio = TipoExamesRepositorio;
    }

    public IActionResult Index()
    {
        List<TipoExameModel> TipoExames = _tipoExamesRepositorio.BuscarTodos();
        return View(TipoExames);
    }

    public IActionResult Criar()
    {
        return View();
    }
    public IActionResult Editar(int id)
    {
        TipoExameModel TipoExame = _tipoExamesRepositorio.ListarPorId(id);
        return View(TipoExame);
    }
    public IActionResult ApagarConfirmacao(int id)
    {
        TipoExameModel TipoExame= _tipoExamesRepositorio.ListarPorId(id);
        return View(TipoExame);

    }

    public IActionResult Apagar(int id)
    {
        try
        {
            bool apagado = _tipoExamesRepositorio.Apagar(id);
            if (apagado)
            {
                TempData["MensagemSucesso"] = " Exame excluido com sucesso!";
            }
            else
            {
                TempData["MensagemErro"] = " Houve um erro ao apagar o exame";

            }
            return RedirectToAction("Index");
        }
        catch (Exception erro)
        {
            TempData["MensagemErro"] = $"Não conseguimos apagar o exame, detalhes do erro: {erro.Message}";
            return RedirectToAction("Index");

        }
    }

    [HttpPost]
    public IActionResult Criar(TipoExameModel TipoExame)
    {
        try
        {
            if (ModelState.IsValid)
            {
                _tipoExamesRepositorio.Adicionar(TipoExame);
                TempData["MensagemSucesso"] = "Exame cadastrado com sucesso";
                return RedirectToAction("Index");
            }
            return View(TipoExame);
        }
        catch (Exception erro)
        {
            TempData["MensagemErro"] = $"Exame não cadastrado, tente novamente. Detalhe do erro {erro.Message}";
            return RedirectToAction("Index");


        }
    }

    [HttpPost]
    public IActionResult Alterar(TipoExameModel TipoExame)
    {
        try
        {
            if (ModelState.IsValid)
            {
                _tipoExamesRepositorio.Atualizar(TipoExame);
                TempData["MensagemSucesso"] = "Exame alterado com sucesso";
                return RedirectToAction("Index");

            }
            return View("Editar", TipoExame);
        }
        catch (Exception erro)
        {
            TempData["MensagemErro"] = $"Não conseguimos atualizar o exame, tente novamente. Detalhe do erro: {erro.Message}";
            return RedirectToAction("Index");
        }
    }
}

Views/TipoExames/ApagarConfirmacao.cshtml
@using Agendamento.Models;

@model TipoExameModel


@{
    ViewData["Title"] = "Confirmação de excluir exame";
}


<div class="text-center">
    <h3 class="display-4"> Realmente deseja excluir o tipo de exame @Model.Nome ? </h3>

</div>

<a class="btn btn-primary " asp-controller="TipoExames" asp-action="Index" role="button">Cancelar exclusão</a>
<a class="btn btn-danger " asp-controller="TipoExames" asp-action="Apagar" asp-route-id="@Model.Id" role="button">Confirmar exclusão</a>

Views/TipoExames/Criar.cshtml
@using Agendamento.Models;

@model TipoExameModel

@{
    ViewData["Title"] = "Cadastro de tipo de exames";
}

<div class="text-center">
    <h1 class="display-4"> Cadastrar tipo de exames</h1>

</div> 


<form asp-controller="TipoExames" asp-action="Criar" method="post">

    @Html.Partial("Form.cshtml")

</form>

Views/TipoExames/Editar.cshtml
@using Agendamento.Models;

@model TipoExameModel



@{
    ViewData["Title"] = "Editar tipo de exame";
}

<div class="text-center">
    <h1 class="display-4"> Editar tipo de exames</h1>

</div>


<form asp-controller="TipoExames" asp-action="Alterar" method="post">
    <input type="hidden" asp-for="Id" />

    @Html.Partial("Form.cshtml")

</form>

Views/TipoExames/Form.cshtml
@using Agendamento.Models;

@model TipoExameModel



<div class="row">

    <div class="form-group">
        <label for="nome">Nome do tipo de exame</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Nome do tipo de exame" />
        @Html.ValidationMessageFor(x => x.Nome)
    </div>
    <div class="form-group col-3">
        <label for="Descricao">Descrição do tipo de exame</label>
        <input type="text" asp-for="Descricao" class="form-control" placeholder="Descrição do tipo de exame" />


        <button type="submit" class="btn btn-primary">Salvar tipo de exame</button>
        <a class="btn btn-secondary " asp-action="Index" asp-controller="TipoExames" role="button">Voltar</a>

    </div>

Views/TipoExames/Index.cshtml
@using Agendamento.Models;


@model List<TipoExameModel>


@{
    ViewData["Title"] = "Cadastro de tipo de exame";

}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="TipoExames" asp-action="Criar">Adicionar novo tipo de exame</a>
    </div>
    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>

    }
    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">

            <button type="button" class="btn btn-danger btn-sm close-alert" arial="Close">X</button>
            @TempData["MensagemErro"]
        </div>

    }
    <br />

    <div class="text-center">
        <h1 class="display-4"> Cadastrar exames</h1>

    </div>


    <form asp-controller="Exames" asp-action="Criar" method="post">

        <ul class="list" id="Exame">
            <h1>Lista tipo de exames</h1>

        </ul>
        @if (Model != null && Model.Any())
        {
            <table class="table" id="table-Exames">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nome</th>
                        <th scope="col">Observações</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>

                    @if (Model != null && Model.Any())
                    {
                        foreach (TipoExameModel TipoExame in Model)
                        {

                            <tr>
                                <th scope="row">@TipoExame.Id</th>
                                <td>@TipoExame.Nome</td>
                                <td>@TipoExame.Descricao</td>
                                <td>
                                    <div class="btn-group" role="group">
                                        <a role="button" class="btn btn-primary display flex" asp-route-id="@TipoExame.Id" asp-controller="TipoExames" asp-action="Editar">Editar</a>
                                        <a role="button" class="btn btn-danger" asp-route-id="@TipoExame.Id" asp-controller="TipoExames" asp-action="ApagarConfirmacao">Apagar</a>

                                    </div>
                                </td>
                            </tr>
                        }



                    }
                </tbody>
            </table>

        }






    </form>