Controllers/ExameController.cs
using Agedamento.Models;
using Agendamento.Models;
using Agendamento.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace Agendamento.Controllers
{
    public class ExameController : Controller
    {
 
            private readonly IExameRepositorio _exameRepositorio;
            private readonly ITipoExamesRepositorio _tipoExamesRepositorio;

            public ExameController(IExameRepositorio exameRepositorio, ITipoExamesRepositorio tipoExamesRepositorio)
            {
                _exameRepositorio = exameRepositorio;
                 _tipoExamesRepositorio = tipoExamesRepositorio;

            }

            public IActionResult Index()
            {
                
                List<ExameModel> exames = _exameRepositorio.BuscarTodos();
                return View(exames);
            }
            public IActionResult Criar()
            {
                   
                   List<TipoExameModel> tipoExames = _tipoExamesRepositorio.BuscarTodos();
                   ViewBag.TipoExames = tipoExames;
                   return View();
            }
            public IActionResult Editar(int id)
            {
                 
                 ExameModel exame = _exameRepositorio.ListarPorId(id);
                 List<TipoExameModel> tipoExames = _tipoExamesRepositorio.BuscarTodos();
                 ViewBag.TipoExames = tipoExames;
                return View(exame);
            }
            public IActionResult ApagarConfirmacao(int id)
            {
                ExameModel exame = _exameRepositorio.ListarPorId(id);
                return View(exame);
            }

            public IActionResult Apagar(int id)
            {
                try
                {
                    bool apagado = _exameRepositorio.Apagar(id);
                    if (apagado)
                    {
                        TempData["MensagemSucesso"] = "Exame apagado com sucesso!";
                    }
                    else
                    {
                        TempData["MensagemErro"] = "Não conseguimos apagar o exame";
                    }
                    return RedirectToAction("Index");
                }
                catch (Exception erro)
                {
                    TempData["MensagemErro"] = $"Não conseguimos apagar o exame, detalhes do erro: {erro.Message}";
                    return RedirectToAction("Index");

                }

            }


            [HttpPost]
            public IActionResult Criar(ExameModel exame)
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        _exameRepositorio.Adicionar(exame);
                        TempData["MensagemSucesso"] = "Exame cadastrado com sucesso";
                        return RedirectToAction("Index");
                    }

                    return View(exame);

                }
                catch (Exception erro)
                {
                    TempData["MensagemErro"] = $"Exame não cadastrado, tente novamente. Detalhe do erro: {erro.Message}";
                    return RedirectToAction("Index");

                }

            }
            [HttpPost]
            public IActionResult Alterar(ExameModel exame)
            {
                try
                {
                
                     if (ModelState.IsValid )
                    {
                    _exameRepositorio.Atualizar(exame);
                        TempData["MensagemSucesso"] = "Paciente alterado com sucesso";
                        return RedirectToAction("Index");
                    }
                    return View("Editar", exame);

                }
                catch (Exception erro)
                {
                    TempData["MensagemErro"] = $"Não conseguimos atualizar os dados do paciente, tente novamente. Detalhe do erro: {erro.Message}";
                    return RedirectToAction("Index");
                }
            }

        }
    }

Controllers/ExamesController.cs
using Agedamento.Data;
using Agedamento.Models;
using Agendamento.Models;
using Agendamento.Repositorio;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

public class ExamesController : Controller
{
    private readonly IExameRepositorio _exameRepositorio;

    public ExamesController(IExameRepositorio ExameRpositorio)
    {
        _exameRepositorio = ExameRpositorio;
    }

    public IActionResult Index()
    {
        List<ExameModel> exames = _exameRepositorio.BuscarTodos();
        return View(exames);
    }

    public IActionResult Criar()
    {
        return View();
    }
    public IActionResult Editar(int id)
    {
        ExameModel exame = _exameRepositorio.ListarPorId(id);
        return View(exame);
    }
    public IActionResult ApagarConfirmacao(int id)
    {
        ExameModel exame = _exameRepositorio.ListarPorId(id);
        return View(exame);

    }

    public IActionResult Apagar(int id)
    {
        try
        {
            bool apagado = _exameRepositorio.Apagar(id);
            if (apagado)
            {
                TempData["MensagemSucesso"] = " Exame excluido com sucesso!";
            }
            else
            {
                TempData["MensagemErro"] = " Houve um erro ao apagar o exame";

            }
            return RedirectToAction("Index");
        }
        catch (Exception erro)
        {
            TempData["MensagemErro"] = $"Não conseguimos apagar o exame, detalhes do erro: {erro.Message}";
            return RedirectToAction("Index");

        }
    }

    [HttpPost]
    public IActionResult Criar(ExameModel exame)
    {
        try
        {
            if (ModelState.IsValid)
            {
                _exameRepositorio.Adicionar(exame);
                TempData["MensagemSucesso"] = "Exame cadastrado com sucesso";
                return RedirectToAction("Index");
            }
            return View(exame);
        }
        catch (Exception erro)
        {
            TempData["MensagemErro"] = $"Exame não cadastrado, tente novamente. Detalhe do erro {erro.Message}";
            return RedirectToAction("Index");


        }
    }

    [HttpPost]
    public IActionResult Alterar(ExameModel exame)
    {
        try
        {
            if (ModelState.IsValid)
            {
                _exameRepositorio.Atualizar(exame);
                TempData["MensagemSucesso"] = "Exame alterado com sucesso";
                return RedirectToAction("Index");

            }
            return View("Editar", exame);
        }
        catch (Exception erro)
        {
            TempData["MensagemErro"] = $"Não conseguimos atualizar o exame, tente novamente. Detalhe do erro: {erro.Message}";
            return RedirectToAction("Index");
        }
    }
}

Views/Exame/ApagarConfirmacao.cshtml
@using Agendamento.Models;

@model ExameModel


@{
    ViewData["Title"] = "Confirmação de excluir exame";
}


<div class="text-center">
    <h3 class="display-4"> Realmente deseja excluir o exame @Model.Nome ? </h3>

</div>

<a class="btn btn-primary " asp-controller="Exame" asp-action="Index" role="button">Cancelar exclusão</a>
<a class="btn btn-danger " asp-controller="Exame" asp-action="Apagar" asp-route-id="@Model.Id" role="button">Confirmar exclusão</a>

Views/Exame/Criar.cshtml
@using Agendamento.Models;

@model ExameModel

@{
    ViewData["Title"] = "Cadastro exames";
}

<div class="text-center">
    <h1 class="display-4"> Cadastrar exames</h1>

</div> 


<form asp-controller="Exame" asp-action="Criar" method="post">

    @Html.Partial("Form.cshtml")

</form>

Views/Exame/Editar.cshtml
@using Agendamento.Models;

@model ExameModel



@{
    ViewData["Title"] = "Editar exame";
}

<div class="text-center">
    <h1 class="display-4"> Editar exame</h1>

</div>


<form asp-controller="Exame" asp-action="Alterar" method="post">
    <input type="hidden" asp-for="Id" />
    @Html.Partial("Form.cshtml")

</form>

Views/Exame/Form.cshtml
@using Agendamento.Models;

@model ExameModel




<div class="row">

    <div class="form-group">
        <label for="nome" >Nome do exame </label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Nome do tipo de exame" />
        @Html.ValidationMessageFor(x => x.Nome)
    </div>
    <div class="form-group col-3">
        <label for="Descricao">Descrição do tipo de exame</label>
        <input type="text" asp-for="Observacoes" class="form-control" placeholder="Observações de exame" />

        <select asp-for="TipoExameId" class="form-control">
            @foreach (var tipoExames in (ViewBag.TipoExames))
            {
                <option value="@tipoExames.Id"> @tipoExames.Nome</option>
                
            }
           
           
        </select>


        <button type="submit" class="btn btn-primary">Salvar o exame</button>
        <a class="btn btn-secondary " asp-action="Index" asp-controller="Exame" role="button">Voltar</a>
  
    </div>
 </div>

Views/Exame/Index.cshtml
@using Agendamento.Models;


@model List<ExameModel>


@{
    ViewData["Title"] = "Cadastro exame";

}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Exame" asp-action="Criar">Adicionar novo exame</a>
    </div>
    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>

    }
    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">

            <button type="button" class="btn btn-danger btn-sm close-alert" arial="Close">X</button>
            @TempData["MensagemErro"]
        </div>

    }
    <br />

    <div class="text-center">
        <h1 class="display-4"> Cadastrar  exames</h1>

    </div>


    <form asp-controller="Exame" asp-action="Criar" method="post">

        <ul class="list" id="Exame">
            <h1>Lista de exames</h1>

        </ul>
        @if (Model != null && Model.Any())
        {
            <table class="table" id="table-Exames">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nome</th>
                        <th scope="col">Observaçãoes</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>

                    @if (Model != null && Model.Any())
                    {
                        foreach (ExameModel exame in Model)
                        {

                            <tr>
                                <th scope="row">@exame.Id</th>
                                <td>@exame.Nome</td>
                                <td>@exame.Observacoes</td>
                                <td>
                                    <div class="btn-group" role="group">
                                        <a role="button" class="btn btn-primary display flex" asp-route-id="@exame.Id" asp-controller="Exame" asp-action="Editar">Editar</a>
                                        <a role="button" class="btn btn-danger" asp-route-id="@exame.Id" asp-controller="Exame" asp-action="ApagarConfirmacao">Apagar</a>

                                    </div>
                                </td>
                            </tr>
                        }



                    }
                </tbody>
            </table>

        }






    </form>