Controllers/ConsultaController.cs
using Agedamento.Models;
using Agendamento.Models;
using Agendamento.Repositorio;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace Agendamento.Controllers
{
    public class ConsultaController : Controller
    {
        private readonly IConsultaRepositorio _consultaRepositorio;
        private readonly IPacientesRepositorio _pacientesRepositorio;
        private readonly ITipoExamesRepositorio _tipoExamesRepositorio;
        private readonly IExameRepositorio _exameRepositorio;
       
        public ConsultaController
         (
            IConsultaRepositorio consultaRepositorio,
            IPacientesRepositorio pacientesRepositorio,
            ITipoExamesRepositorio tipoExamesRepositorio,
            IExameRepositorio exameRepositorio
         )
        {
            _consultaRepositorio = consultaRepositorio;
            _pacientesRepositorio = pacientesRepositorio;
            _tipoExamesRepositorio = tipoExamesRepositorio;
            _exameRepositorio = exameRepositorio;
        }


        public IActionResult Index()
        {
            List<ConsultaModel> consulta = _consultaRepositorio.BuscarTodos();
            return View(consulta);
        }


        public IActionResult Criar()
        {
            DateTime dataHoraAtual = DateTime.Now;

 
            string protocolo = $"{dataHoraAtual:yyyyMMdd-HHmmss}";
            string filtro = HttpContext.Request.Query["filtro"];
             List<PacientesModel> pacientes = _pacientesRepositorio.BuscarPorNomeCpf(filtro);
            ViewBag.pacientes = pacientes;
            ViewBag.Protocolo = protocolo;

          

            List<TipoExameModel> TipoExame = _tipoExamesRepositorio.BuscarTodos();
            ViewBag.TipoExame =TipoExame;

            
            
            ViewBag.exames = TipoExame;
            return View();
        }

        
    [HttpPost]
        public IActionResult Criar(ExameModel exame)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _exameRepositorio.Adicionar(exame);
                    TempData["MensagemSucesso"] = "Consulta marcada com sucesso";
                    return RedirectToAction("Index");
                }
                return View(exame);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Consulta não agendada, tente novamente{erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Agendar(ConsultaModel consulta)
        {
            if (!_consultaRepositorio.DataHoraConflitante(consulta))
            {
                consulta.Protocolo = Guid.NewGuid().ToString();
                _consultaRepositorio.Adicionar(consulta);
                TempData["MensagemSucesso"] = "Consulta marcada com secesso";

                return RedirectToAction("Index", consulta);
            }
            else
            {
                ModelState.AddModelError("DataHora", "Já existe uma consulta agendada para este horário.");
               return this.Criar();
            }

        }
        [HttpGet]
        public IActionResult CarregarExames(int tipoExameId)
        {
            var exames = _exameRepositorio.BuscarPorTipo(tipoExameId); 
            return Json(exames);
        }
        [HttpGet]
            public IActionResult buscarPaciente (string filtroPaciente)
        {
            var Pacientes = _pacientesRepositorio.BuscarPorNomeCpf(filtroPaciente);
              return Json(Pacientes);
        }

    }
}

Controllers/PacientesController.cs
using Agedamento.Models;
using Agendamento.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace Agedamento.Controllers
{
    public class PacientesController : Controller
    {
        private readonly IPacientesRepositorio _pacientesRepositorio;
        public PacientesController(IPacientesRepositorio PacientesRepositorio)
        {
            _pacientesRepositorio = PacientesRepositorio;
        }
        public IActionResult Index()
        {
            List<PacientesModel> pacientes = _pacientesRepositorio.BuscarTodos();
            return View(pacientes);
        }
        public IActionResult Criar()
        {
            return View();
        }
        public IActionResult Editar(int id)
        {
             PacientesModel paciente =  _pacientesRepositorio.ListarPorId(id);
            return View(paciente);
        }
        public IActionResult ApagarConfirmacao(int id)
        {
            PacientesModel paciente = _pacientesRepositorio.ListarPorId(id);
            return View(paciente);
        }

        public IActionResult Apagar(int id)
        {
            try
            {
               bool apagado = _pacientesRepositorio.Apagar(id);
                if (apagado)
                {
                    TempData["MensagemSucesso"] = "Paciente apagado com sucesso!";
                }
                else
                {
                    TempData["MensagemErro"] = "Não conseguimos apagar o paciente";
                }
                return RedirectToAction("Index");
            }
            catch(Exception erro)
            {
                TempData["MensagemErro"] = $"Não conseguimos apagar o paciente, detalhes do erro: {erro.Message}";
                return RedirectToAction("Index");

            }

        }


        [HttpPost]
        public IActionResult Criar(PacientesModel paciente)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _pacientesRepositorio.Adicionar(paciente);
                    TempData["MensagemSucesso"] = "Paciente cadastrado com sucesso";
                    return RedirectToAction("Index");
                }

                return View(paciente);

            }
            catch(Exception erro)
            {
                TempData["MensagemErro"] = $"Paciente não cadastrado, tente novamente. Detalhe do erro: {erro.Message }";
                return RedirectToAction("Index");

            }
            
        }
        [HttpPost]
        public IActionResult Alterar(PacientesModel paciente)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _pacientesRepositorio.Atualizar(paciente);
                    TempData["MensagemSucesso"] = "Paciente alterado com sucesso";
                    return RedirectToAction("Index");
                }
                return View("Editar", paciente);

            }
            catch(Exception erro)
            {
                TempData["MensagemErro"] = $"Não conseguimos atualizar os dados do paciente, tente novamente. Detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

Views/Consulta/Agendar.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>

</body>
</html>

Views/Consulta/Criar.cshtml
@using Agendamento.Models;

@model ConsultaModel

@{
    ViewData["Title"] = "Cadastro Consulta";
}

<div class="text-center">
    <h1 class="display-4"> Marcação de  Consultas</h1>

</div> 




    @Html.Partial("Form.cshtml")

Views/Consulta/Form.cshtml
@using Agendamento.Models;

@model ConsultaModel




<div class="container row" >
    <h1 class="mt-5">Cadastro de Consulta</h1>

    <div class="form-group">
        <label for="filtro">Buscar pacientes</label>
        <input type="text" id="filtroPaciente" class="form-control" placeholder="Buscar por nome ou cpf" />
        
    </div>
        <button  id="buscarPaciente" class="btn btn-primary">Buscar Paciente</button>
    <a class="btn btn-secondary " id="cadastrar" style="visibility: hidden;" asp-action="Paciente" asp-controller="Pacientes" role="button">Criar</a>

    <form asp-controller="Consulta" asp-action="Agendar" method="post">
        <div class="form-group col-6">
            <label for="paciente" class="form-label">Pacientes:</label>
            <select asp-for="PacienteId" class="form-select" id="paciente" name="PacienteId" required>

    </select>

        </div>

            <label for="tipoExame">Selecione o Tipo de Exame:</label>
            <select id="tipoExame">
                <option value="">Selecione</option>
                @foreach (var tipoExame in ViewBag.TipoExame)
                {
                    <option value="@tipoExame.Id">@tipoExame.Nome</option>
                }
            </select>

        <div class="form-group col-6">
            <label for="Exame" class="form-label">Exame:</label>
            <select asp-for="ExameId" class="form-select" id="Exame" name="ExameId" required>
              

            </select>
   
        
        <div class="form-group col-3">
            <label for="dataHora">Selecione Data e Hora:</label>
            <input type="datetime-local" id="dataHora" name="dataHora" required>
        </div>
           

        <div class="form-group col-3  ">
            <label for="Protocolo">Protocolo</label>
            <input disabled type="text" value="@ViewBag.Protocolo" asp-for="Protocolo" class="form-control"  />
             
        </div>

        <button type="submit" class="btn btn-primary">Cadastrar Consulta</button>
        <a class="btn btn-secondary " asp-action="Index" asp-controller="Consulta" role="button">Voltar</a>

    </form>

</div>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    $(document).ready(function () {
        
         $("#tipoExame").change(function ()
         {
             
            var tipoExameId = $(this).val();
            $.ajax({
                url: "/Consulta/CarregarExames", 
                type: "GET",
                data: { tipoExameId: tipoExameId },
                success: function (data) {
                    
                    $("#Exame").empty();
                    $.each(data, function (i, exame) {
                        console.log(exame)
                        $("#Exame").append('<option value="' + exame.id + '">' + exame.nome + '</option>');
                    });
                },
                error: function () {
                    console.error("Erro ao carregar exames.");
                }
            });
        });

        $("#buscarPaciente").click(function () {

            var filtroPaciente = $("#filtroPaciente").val();
            $.ajax({
                url: "/Consulta/buscarPaciente",
                type: "GET",
                data: { filtroPaciente: filtroPaciente },
                success: function (data) {
                    
                    if (data.length != 0)
                    { 
                        $("#cadastrar").css("visibility", "hidden")
                    }else 
                    {
                        $("#cadastrar").css("visibility", "visible")
                       
                    }

                    $("#paciente").empty();
                    $.each(data, function (i, paciente) {

                        $("#paciente").append('<option value="' + paciente.id + '">' + paciente.nome + '</option>');
                    });
                },
                error: function () {
                    console.error("Erro ao carregar os pacientes.");
                }
            });
        });
    });
</script>

Views/Consulta/Index.cshtml
@using Agendamento.Models;


@model List<ConsultaModel>


@{
    ViewData["Title"] = "Cadastro de consulta";

}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Consulta" asp-action="Criar">Adicionar no consulta</a>
    </div>
    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>

    }
    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">

            <button type="button" class="btn btn-danger btn-sm close-alert" arial="Close">X</button>
            @TempData["MensagemErro"]
        </div>

    }
    <br />

    <div class="text-center">
        <h1 class="display-4">Consulta</h1>

    </div>


    <form asp-controller="Consulta" asp-action="Criar" method="post">

        <ul class="list" id="Consulta">
            <h1>Lista Consultas</h1>

        </ul>
        @if (Model != null && Model.Any())
        {
            <table class="table" id="table-Consulta">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nome</th>
                        <th scope="col">Observaçãoes</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>

                    @if (Model != null && Model.Any())
                    {
                        foreach (ConsultaModel consulta in Model)
                        {
                            <tr>
                                <th scope="row">@consulta.Id</th>
                               
                                <td>@consulta.Paciente</td>
                                
                                <td>@consulta.</td>
                                <td>
                                    <div class="btn-group" role="group">
                                        <a role="button" class="btn btn-primary display flex" asp-route-id="@consulta.Id" asp-controller="Consulta" asp-action="Editar">Editar</a>
                                        <a role="button" class="btn btn-danger" asp-route-id="@consulta.Id" asp-controller="Consulta" asp-action="ApagarConfirmacao">Apagar</a>

                                    </div>
                                </td>
                            </tr>
                        }



                    }
                </tbody>
            </table>

        }






    </form>